version: '3.8'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  
networks:
  oauth:
  
services:
  oauth-client:
    container_name: oauth-client
    image: oauth-client:latest
    build: 
      context: .
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8089"]



















